# Configuration fragment for a solid bridge between case and wrist rest.

bottom-plates:
  combine: true
wrist-rest:
  include: true
  style: solid
secondaries:
  wrb-case:
    anchoring:
      anchor: front3
      side: SSE
      segment: 3
      extrinsic-offset: [-16, 0, -8]
  wrb-rest:
    anchoring:
      anchor: plinth-left
      extrinsic-offset: [0, 0, -3]
  wrb1-west:
    anchoring:
      anchor: wrb-case
  wrb1-top:
    anchoring:
      anchor: wrb1-west
      extrinsic-offset: [15, 0, 3]
    size: [8, 2, 8]
  wrb1-east:
    anchoring:
      anchor: wrb1-west
      extrinsic-offset: [30, 0, 0]
  wrb2-bottom:
    anchoring:
      anchor: wrb1-top
      extrinsic-offset: [0, -15, -3]
    size: [20, 1, 1]
  wrb2-top:
    anchoring:
      anchor: wrb2-bottom
    size: 8
  wrb3-bottom:
    anchoring:
      anchor: wrb2-bottom
      extrinsic-offset: [0, -25, 0]
    size: [20, 1, 1]
  wrb3-top:
    anchoring:
      anchor: wrb3-bottom
    size: 8
  wrb4-west:
    anchoring:
      anchor: wrb1-west
      extrinsic-offset: [0, -55, 0]
  wrb4-top:
    anchoring:
      anchor: wrb1-top
      extrinsic-offset: [0, -55, 0]
    size: [8, 12, 8]
  wrb4-east:
    anchoring:
      anchor: wrb1-east
      extrinsic-offset: [0, -55, 0]
tweaks:
  wrist-rest-bridge-main-body:
    - chunk-size: 2
      to-ground: true
      hull-around:
      - hull-around:
        - [wrb1-west]
        - [wrb1-top]
        - [wrb1-east]
      - hull-around:
        - [wrb2-bottom]
        - [wrb2-top]
  wrist-rest-bridge-middle:
    - chunk-size: 2
      to-ground: true
      hull-around:
      - hull-around:
        - [wrb2-bottom]
        - [wrb2-top]
      - hull-around:
        - [wrb3-bottom]
        - [wrb3-top]
  wrist-rest-bridge-rest:
    - chunk-size: 2
      to-ground: true
      hull-around:
      - hull-around:
        - [wrb3-bottom]
        - [wrb3-top]
      - hull-around:
        - [wrb4-west]
        - [wrb4-top]
        - [wrb4-east]
      - hull-around:
        - [wrb-rest]
        - [plinth-mid0]
        - [plinth-mid1]
