# Configuration fragment for mutual anchoring.

# To understand the difference between this and the “caseside” option (a
# neighbouring file), read about “mutual” authority in the manual for wrist
# rest mount configuration (i.e. doc/options-wrist-rest-mounts.md).

wrist-rest:
  include: true
  style: threaded
  mounts:
  - fasteners:
      bolt-properties:
        m-diameter: 3
        head-type: button
        total-length: 50
      heights: [7]
    authority: mutual
    blocks:
      width: 13
      partner-side:
        anchoring:
          anchor: t4
          side: NNE
          segment: 3
          extrinsic-offset: [7, -6, 0]
        depth: 10
      wrist-side:
        anchoring:
          anchor: plinth-left
          extrinsic-offset: [10, 4, 0]
        depth: 8
    aliases:
      blocks:
        wr0p: partner-side
        wr0w: wrist-side
      nuts:
        wr0p0: [partner-side, 0]
        wr0w0: [wrist-side, 0]
tweaks:
  wrist-rest-nut-pockets:
  - to-ground: true
    cut: true
    hull-around: [[wr0w0]]
