# Bundled non-neutral basic model build parameters.
# These should be pretty safe to use with any keyboard design and are easy to override.

keys:
  styles:
    # A non-printable preview of a DSA profile key:
    default:
      style: maquette
      skirt-length: 4.6
      top-size: [12.7, 12.7, 3.3]
by-key:
  parameters:
    plate:
      use-key-style: true
    layout:
      clearance:
        nominal: 8  # Approximate DSA cap height above plate.
    channel:
      height: 20
      top-width: 10
    wall:
      segments:
        "0":
          size: 2
          intrinsic-offset: [0,  0, 0]
        "1":
          size: 2
          intrinsic-offset: [0,  1, -1]  # Top bevel.
        "2":
          size: 2
          intrinsic-offset: [0,  0, -8]  # Perpendicular wall.
        "3":
          size: 2
          intrinsic-offset: [0, -1, -1]  # Bottom bevel.
main-body:
  rear-housing:
    thickness:
      walls: 2.5
      roof: 2.5
    bevel:
      exterior: 1
      interior: 1
  back-plate:
    fasteners:
      bolt-properties:
        m-diameter: 4
        head-type: countersunk
central-housing:
  adapter:
    fasteners:
      bolt-properties:
        m-diameter: 3
        head-type: countersunk
        total-length: 8.5
flanges:
  main-bottom-plate:
    bottom: true
    bolts:
      include: true
      bolt-properties:
        m-diameter: 3
        head-type: countersunk
        point-type: cone
        total-length: 8.5
        channel-length: 1
    bosses:
      segments:
        "0":
          size: [7, 1]
        "1":
          size: [4, 1]
          intrinsic-offset: [0, 0, -6]
  central-housing-bottom-plate:
    bottom: true
    bolts:
      include: true
      bolt-properties:
        m-diameter: 3
        head-type: countersunk
        point-type: cone
        total-length: 8.5
        channel-length: 1
    bosses:
      segments:
        "0":
          size: [7, 1]
        "1":
          size: [4, 1]
          intrinsic-offset: [0, 0, -6]
  wrist-rest-bottom-plate:
    bottom: true
    bolts:
      include: true
      bolt-properties:
        m-diameter: 3
        head-type: countersunk
        point-type: cone
        total-length: 8.5
        channel-length: 1
    bosses:
      segments:
        "0":
          size: [7, 1]
        "1":
          size: [4, 1]
          intrinsic-offset: [0, 0, -6]
mcu:
  type: promicro
  support:
    lock:
      width-factor: 0.45
      fastener-properties:
        m-diameter: 3
        head-type: countersunk
      plate:
        clearance: 0.9
      socket:
        thickness: 1.5
      bolt:
        clearance: 2.5
        overshoot: 1
        mount-length: 7
        mount-thickness: 6
resolution:
  include: true
dfm:
  error-general: -0.4
  bottom-plate:
    fastener-plate-offset: -0.15
