# Configuration fragment for visualization of an assembled keyboard.
# You probably don’t want to print with these settings.

keys:
  preview: true
central-housing:
  preview: true
wrist-rest:
  preview: true
custom-bodies:
  # This section names custom bodies defined in various bundled configurations.
  # They are turned off, so that they will be rendered as part of their parent
  # bodies, resulting in a preview of an assembled keyboard.
  left-hand-bookend:
    include: false
  right-hand-bookend:
    include: false
  thumb-cluster:
    include: false
bottom-plates:
  preview: true
mcu:
  preview: true
  support:
    preview: true
