# A configuration fragment for Tom Short’s Dactyl-ManuForm, ca. v0.4.

# The long-term goal with this file is to have it produce Short’s design
# through the DMOTE application for upstream compatibility.
# Similarity is checked by placing Short’s “right-4x5.stl” file
# in the things/scad/ folder and then injecting it into a DMOTE output:
#
# $ echo '%import("right-4x5.stl");' >> things/scad/right-hand-body-main.scad
#
# In that Linux-style shell command, $ represents your prompt.
#
# As of DMOTE v0.6.0, the application is still missing the wire hook
# feature on the original Dactyl-ManuForm, though it could be imitated
# with the tweaks feature. A vertex-perfect imitation would be laborious
# in any case.

keys:
  styles:
    default:  # Rough approximation of SA family.
      style: maquette
      switch-type: mx
      skirt-length: 5.75
      top-size: [12.7, 12.7, 6]
      unit-size: [1, 1]
    big:
      style: maquette
      switch-type: mx
      skirt-length: 5.75
      top-size: [12.7, 20, 6]
      unit-size: [1, 1.5]
key-clusters:
  main:
    anchoring:
      anchor: origin
      intrinsic-rotation: [0, 0.26, 0]
      extrinsic-offset: [1, 0, 12.9]
    matrix-columns:
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 1
    aliases:
      m00: [0, first]
      m01: [1, first]
      m02: [2, first]
      m03: [3, first]
      m04: [4, first]
      mcu-base-key: [0, 0]
      back0: [0, last]
      back1: [1, last]
      back2: [2, last]
      back3: [3, last]
      right0: [last, 0]
  thumb0:
    anchoring:
      anchor: m00
      preserve-orientation: true
      intrinsic-rotation: [0.1745, -0.4014, 0.1745]
      extrinsic-offset: [-1.8, -28.3, -5.9]
    matrix-columns:
    - rows-above-home: 0
    - rows-above-home: 0
    aliases:
      thumb-tr: [1, 0]  # Top right.
      thumb-tl: [0, 0]
  thumb1:
    anchoring:
      anchor: thumb-tl
      preserve-orientation: true
      intrinsic-rotation: [-0.02, -0.59, 0.94]
      extrinsic-offset: [3.5, -26, -15]
    matrix-columns:
    - rows-above-home: 1
    - rows-above-home: 1
    aliases:
      thumb-mr: [1, 0]
      thumb-ml: [1, 1]
      thumb-br: [0, 0]
      thumb-bl: [0, 1]
by-key:
  parameters:
    plate:
      use-key-style: false
      size: [15.5, 14, 4]
    layout:
      matrix:
        separation:
          column: 1.3
          row: 1.2
    wall:
      extent: 2
      to-ground: true
      segments:
        "0":
          size: [2.1, 2.1, 4]
          intrinsic-offset: [0, 0, 0]
        "1":
          size: [2.1, 2.1, 4]
          intrinsic-offset: [0, 2, -1]
        "2":
          size: [2.1, 2.1, 4]
          intrinsic-offset: [0, 5, -14]
        "3":
          size: [2.1, 2.1, 4]
  clusters:
    main:
      parameters:
        layout:
          matrix:
            neutral:
              column: 3
          pitch:
            progressive: 0.27
          roll:
            progressive: 0.09
      columns:
        first:
          sides:
            # Wider left-side wall to fit MCU.
            WNW:
              parameters:
                wall:
                  extent: 3
                  segments:
                    "1":
                      intrinsic-offset: [0, 8.5, -7]
                    "2":
                      intrinsic-offset: [0, 1, -3]
                    "3":
                      intrinsic-offset: [0, -2, -10]
            WSW:
              parameters:
                wall:
                  extent: 3
                  segments:
                    "1":
                      intrinsic-offset: [0, 8.5, -7]
                    "2":
                      intrinsic-offset: [0, 1, -3]
                    "3":
                      intrinsic-offset: [0, -2, -10]
            # No internal wall against thumb clusters.
            SSE:
              parameters:
                wall:
                  extent: 0
                  to-ground: false
            SSW:
              parameters:
                wall:
                  extent: 0
                  to-ground: false
        "1":
          sides:
            SSE:
              parameters:
                wall:
                  extent: 0
                  to-ground: false
            SSW:
              parameters:
                wall:
                  extent: 0
                  to-ground: false
        "2":
          parameters:
            layout:
              translation:
                mid: [0, 2.82, -4.5]
            wall:
              extent: 0
              to-ground: false
          sides:
            NNE:
              parameters:
                wall:
                  extent: 2
                  to-ground: true
            NNW:
              parameters:
                wall:
                  extent: 2
                  to-ground: true
        "3":
          sides:
            ENE:
              parameters:
                wall:
                  extent: 0
                  to-ground: false
            ESE:
              parameters:
                wall:
                  extent: 0
                  to-ground: false
            SSE:
              parameters:
                wall:
                  segments:
                    "2":
                      intrinsic-offset: [3, 5, -14]
        "4":
          parameters:
            layout:
              translation:
                mid: [-0.3, -12, 5.64]
          sides:
            SSW:
              parameters:
                wall:
                  segments:
                    "2":
                      intrinsic-offset: [-7, 5, -14]
    thumb0:
      parameters:
        key-style: big
        plate:
          use-key-style: true
        wall:
          extent: 0
          to-ground: false
          segments:
            "0":
              size: [0.1, 0.1, 4]
      columns:
        last:
          parameters:
            layout:
              translation:
                early: [-0.7, -5.2, -2.2]
          sides:
            ESE:
              parameters:
                wall:
                  segments:
                    "0":
                      size: [2.1, 2.1, 4]
                      intrinsic-offset: [-1, -1, 0]
            SSE:
              parameters:
                wall:
                  segments:
                    "0":
                      size: [2.1, 2.1, 4]
                      intrinsic-offset: [-1, -1, 0]
    thumb1:
      parameters:
        layout:
          matrix:
            neutral:
              column: 1
            separation:
              column: 1
      columns:
        first:
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.26
                  translation:
                    early: [0.2, -0.8, 1.7]
            last:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.07
                  roll:
                    intrinsic: -0.02
                  yaw:
                    intrinsic: -0.03
                  translation:
                    early: [0.1, 0.3, 5.4]
          sides:
            SSW:
              parameters:
                wall:
                  segments:
                    "2":
                      intrinsic-offset: [0, 3, -8]
            NNW:
              parameters:
                wall:
                  segments:
                    "2":
                      intrinsic-offset: [0, 3, -8]
        last:
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.14
                  roll:
                    intrinsic: -0.02
                  yaw:
                    intrinsic: -0.08
                  translation:
                    early: [1.6, 0.6, 3.15]
            last:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.02
                  roll:
                    intrinsic: -0.02
                  yaw:
                    intrinsic: -0.20
                  translation:
                    early: [0.5, 7.5, 5.2]
      sides:
        ENE:
          parameters:
            wall:
              extent: 0
              to-ground: false
        ESE:
          parameters:
            wall:
              extent: 0
              to-ground: false
secondaries:
  back-plane:
    anchoring:
      anchor: back0
      side: NNE
      segment: 2
    override: [null, null, 3]
main-body:
  reflect: true
  bottom-plate:
    include: true
flanges:
  main-bottom-plate:
    include: true
    bottom: true
    bolts:
      include: true
      bolt-properties:
        m-diameter: 3  # Speculation; Short may have used non-metric.
        head-type: countersunk
        point-type: cone  # Design for manufacturing: Easy printing.
        total-length: 6
    inserts:
      include: true
      length: 3.8
      height: 2
      diameter:
        top: 5.1
        bottom: 5.31
    bosses:
      include: true
      segments:
        "0":
          size: [8, 1]  # 6.91 in Short’s original, but this is more robust with
                        # a thin bottom plate.
        "1":
          style: sphere
          size: 6.7
          intrinsic-offset: [0, 0, -6]
    positions:
      - anchoring:
          anchor: thumb-ml
          side: N
          segment: 2
      - anchoring:
          anchor: back0
          side: W
          segment: 2
          intrinsic-offset: [-3, 2, 0]
      - anchoring:
          anchor: back3
          side: N
          segment: 2
      - anchoring:
          anchor: right0
          side: E
          segment: 2
          intrinsic-offset: [-1, 0, 0]
      - anchoring:
          anchor: m02
          side: S
          segment: 2
          intrinsic-offset: [2, -4, 0]
tweaks:
  webbing:
    - above-ground: true
      chunk-size: 3
      hull-around:  # Between the two thumb clusters.
      - [thumb-tl, NW, 0]
      - [thumb-ml, NE, 0]
      - [thumb-tl, SW, 0]
      - [thumb-ml, SE, 0]
      - [thumb-tl, SE, 0]
      - [thumb-mr, NE, 0]
      - [thumb-tr, SW, 0]
      - [thumb-mr, SE, 0]
      - [thumb-tr, SE, 0]
    - above-ground: true
      chunk-size: 3
      hull-around:  # Between thumb0 and the main cluster.
      - [thumb-tl, NW, 0]
      - [m00, SSW, 0]
      - [thumb-tl, NE, 0]
      - [m00, SSE, 0]
      - [thumb-tr, NNW, 0, 1]
      - [m01, SSW, 0]
      - [thumb-tr, NNE, 0, 1]
      - hull-around:
        - [m01, SSE, 0]
        - [m02, WNW, 0]
      - [thumb-tr, ENE, 0, 1]
      - hull-around:
        - [m02, WNW, 0]
        - [m02, WSW, 0]
      - [thumb-tr, ESE, 0, 1]
      - [m02, SSW, 0]
      - hull-around:
        - [m02, SSE, 0]
        - [m03, WSW, 0]
  near-low-corner:
    - above-ground: true
      chunk-size: 3
      hull-around:
      - [m03, NE]
      - [m04, SW]
      - [m03, SE]
      - [m04, SSW, 0, 2]
      - [m03, SSE, 0, 2]
    - to-ground: true
      hull-around:
      - [m04, SSW, 2]
      - [m03, SSE, 2]
  to-floor:
    - to-ground: true
      hull-around:
      - [m00, WSW, 3]
      - [thumb-ml, NNE, 2]
    - to-ground: true
      hull-around:
      - [thumb-ml, NNW, 2]
      - [thumb-bl, NNE, 2]
    - to-ground: true
      hull-around:
      - [m03, SSW, 2]
      - [thumb-tr, SSE, 2]
    - to-ground: true
      hull-around:
      - [thumb-tr, SSE, 2]
      - [thumb-mr, SSE, 2]
    - to-ground: true
      hull-around:
      - [thumb-mr, SSW, 2]
      - [thumb-br, SSE, 2]
  bottom-plate-only:
    - at-ground: true
      hull-around:
      - [m03, E, 2]
      - [m03, ESE, 2]
      - [m03, SSE, 2]
      - [m03, SSW, 2]
    - at-ground: true
      hull-around:
      - [thumb-mr, SSE, 2]
      - [thumb-ml, NNE, 2]
      - [m00, WSW, 2]
      - [m03, NE]
      - [thumb-tr, SSE, 2]
  thumb-to-finger-gap:
    - above-ground: true
      at-ground: true
      chunk-size: 3
      hull-around:
      - [m00, WSW, 0, 1]
      - [m00, WSW, 2, 3]
      - [thumb-tl, WNW, 0]
      - [thumb-ml, NNE, 2]
      - [thumb-ml, NNE, 0, 1]
    - above-ground: true
      shadow-ground: true  # Better than at-ground here for one tiny detail.
      chunk-size: 2
      hull-around:
      - [thumb-mr, SSE, 0, 2]
      - hull-around:
        - [thumb-tr, SSE, 0, 2]
        - [thumb-tr, ESE, 0, 1]
      - [m03, SSW, 0, 2]
  hole-through-big-port:
    - {above-ground: true, cut: true,
       anchoring: {anchor: big-port, side: S, intrinsic-offset: [0, 0, 5]},
       size: [10.78, 13, 5]}
  hole-through-small-port:
    - {above-ground: true, cut: true,
       anchoring: {anchor: small-port},
       size: [6.5, 20, 13.6]}
mcu:
  include: true
  type: promicro
  anchoring:
    anchor: back-plane
    intrinsic-offset: [-20, -16, 12]
    intrinsic-rotation: [0, π/2, 0]
  support:
    shelf:
      include: true
      extra-space: [3, 19.9, 0.43]
      thickness: 3
      rim:
        lateral-thickness: 4
        overhang-thickness: 4
        overhang-width: 3
        offsets: [-34.9, 0]
ports:
  big-port:
    # This models an unknown variety of RJ9 socket.
    include: true
    type: custom
    size: [10.78, 9, 18.38]
    alignment:
      side: NE
      segment: 2
    anchoring:
      anchor: back-plane
      intrinsic-offset: [-2, 5, -1]
    holder:
      include: true
      alias: big-holder
      thickness: 2
  small-port:
    # This models an unknown variety of USB socket.
    include: true
    type: custom
    size: [6.5, 10, 13.6]
    alignment:
      side: NW
      segment: 2
    anchoring:
      anchor: back-plane
      intrinsic-offset: [9, 5, -1]
    holder:
      include: true
      alias: small-holder
      thickness: 2
