# A configuration fragment changing the Dactyl-ManuForm,
# replacing the MCU shelf with a slim gripper that exposes the
# connector on the MCU directly through the case wall.

tweaks:
  hole-through-small-port: null  # Disabled; replaced by gripper.
  mcu-grip:
    - above-ground: true
      hull-around:  # A bar at the rear end of the MCU PCBA.
      - [mcu-grip-base]
      - [mcu-grip-plate]
    - above-ground: true
      hull-around:  # A thick support beam descending from the key cluster.
      - [mcu-grip-base]
      - [back0, ESE, 0]
      - [back1, WSW, 0]
      - [mcu-base-key, ENE, 0]
mcu:
  type: promicro
  anchoring:  # Override base configuration file.
    anchor: big-port
    intrinsic-rotation: [0, 0, 0]  # Lie flat.
    intrinsic-offset: [18, 0, -8]  # Move in low beside big-port.
  support:
    shelf:
      include: false
ports:
  small-port:
    include: false  # Obviated by direct exposure of MCU connector.
secondaries:
  mcu-grip-base:
    anchoring:
      anchor: mcu-pcba
      side: S
      intrinsic-offset: [0, -2, 2]
    size: [5, 4, 7]
  mcu-grip-plate:
    anchoring:
      anchor: mcu-pcba
      side: S
    size: [20, 2, 3]
